/// Generated by AssetsRefGenerator on 2021/10/17
class Res {
  static const String estrelas = "assets/estrelas.jpg";
  static const String logo = "assets/logo.png";
  static const String logo2 = "assets/logo2.png";
  static const String logo3 = "assets/logo3.png";
}
